#!/bin/bash
## WARNING!! STILL WIP. THIS WAS RUSHED AND
## NEEDS TO BE MODIFIED (I HAVENT EVEN USED IT YET).
## lets set some colors first:
declare -r GREEN="\033[0;32m"
declare -r RED="\033[0;31m"
declare -r YELLOW="\033[0;33m"
RESET=$(tput sgr0)

function echo_green {
  echo -e "${GREEN}$1"; tput sgr0
}
function echo_red {
  echo -e "${RED}$1"; tput sgr0
}
function echo_yellow {
  echo -e "${YELLOW}$1"; tput sgr0
}

# OSX brew casks packages:
## always a good idea to update brew before continuing:
brew cask update

## upgrade any current casks:
brew cask upgrade

### formulas to be installed:
echo_yellow "\nDetermining if formulas need installed on this machine or already exist:"
declare -a CASKS=(
gns3
github
iterm2
java
keybase
vagrant
vault
virtualbox
virtualbox-extension-pack
xquartz)

## determine if formula exists on machine. if not ask to install it:
for ((i = 0; i < ${#CASKS[@]}; ++i)); do
  echo -e "Determining if ${YELLOW}${CASKS[i]}${RESET} is already installed:"
  if ! brew cask list | grep ${CASKS[i]} > /dev/null; then
    read -p "Formula ${RED}${CASKS[i]}${RESET} not found! Should it be installed? (y/n) " yn
    case $yn in
        [Yy]* ) brew cask install ${CASKS[i]} ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
    else echo -e "${GREEN}${CASKS[i]}${RESET} is already installed on this machine!\n"
  fi
done
